### ISSUE TITLE
deps: Bump piping-server to 1.0.0

### ISSUE THREAD

**Issue by peaceiris** [nwtgck/hidden-piping-server#43]
The title says it all. #42

I cannot wait for hidden-piping-server v1.0.0 :-)

**Comment by nwtgck** [comment]
@peaceiris Merged!

**Comment by peaceiris** [comment]
Thank you!!!!!!!!!!!!!!!!!

Will the Docker image be updated?

**Comment by nwtgck** [comment]
Thanks. I'll.

**Comment by nwtgck** [comment]
Now, docker image is being created on Docker Hub. Wait for a while.

**Comment by nwtgck** [comment]
The images has been updated!

**Comment by peaceiris** [comment]
I tried to use the docker image v0.1.1

It worked well! Congrats release v1 🎉
